### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by lampatt** [sonichandni/Attendance-Management-System#1]
l am unable to login at the login page. l have tried all the login details from the database but won't work. please advise.

**Comment by lampatt** [comment]
Resolves am able to login after changing the database name to same as yours. but l also enter this error: 
Fatal error: Uncaught Error: Call to undefined function split() in C:\xampp\htdocs\Attendance-Management-System-master\Attendance-Management-System-master\Database\Controler.php:844 Stack trace: #0 C:\xampp\htdocs\Attendance-Management-System-master\Attendance-Management-System-master\academic_year.php(2): include() #1 {main} thrown in C:\xampp\htdocs\Attendance-Management-System-master\Attendance-Management-System-master\Database\Controler.php on line 844

How can l resolve it

**Comment by developers-desk** [comment]
Hi,

You can use below credentials for testing:-

**Admin**
Username: chandnisoni@gmail.com
Password: chandnisoni

**Faculty**
Username: chandni@gmail.com
Password : chandnisoni

**Comment by Uddeshya08** [comment]
How can  change the username and password from database or php file

**Comment by developers-desk** [comment]
You can change it from data base or directly in sql file, before importing the database.
