### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by lampatt** [sonichandni/Attendance-Management-System#2]
Fatal error: Uncaught Error: Call to undefined function split() in C:\xampp\htdocs\Attendance-Management-System-master\Attendance-Management-System-master\Database\Controler.php:844 Stack trace: #0 C:\xampp\htdocs\Attendance-Management-System-master\Attendance-Management-System-master\academic_year.php(2): include() #1 {main} thrown in C:\xampp\htdocs\Attendance-Management-System-master\Attendance-Management-System-master\Database\Controler.php on line 844

**Comment by developers-desk** [comment]
Hi,
This happens because spilt() function has been deprecated in PHP 5.3.0. I have made changes for solving this issue.
