### ISSUE TITLE
Warning: Invalid argument supplied

### ISSUE THREAD

**Issue by lampatt** [sonichandni/Attendance-Management-System#3]
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\Attendance-Management-System-master\Attendance-Management-System-master\view_sub.php on line 30

please assist resolve this issue

**Comment by developers-desk** [comment]
Hi,
I have made changes in database as well as in code. You can clone the whole project again and use it without any issue. Hope it will help.
Thank you.

**Comment by lampatt** [comment]
Thank you very much Sonia, l will try that and get back to you. Really appreciate your assistance and prompt response.

God bless you.

Patrick
________________________________

**Comment by developers-desk** [comment]
@lampatt 
Your welcome Patrick

By the way my name is Chandni not Sonia :)

**Comment by lampatt** [comment]
Very Sorry Chandni for the wrong name. l did clone the project again but it keep giving me the same error message. Can you please send me the latest version please.

Thank you very much for your patience and assistance.

Kind regards.

Patrick
________________________________

**Comment by developers-desk** [comment]
have you change the database?

**Comment by lampatt** [comment]
No l have not changed the database. Let me do that and try again and get back to you then.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lampatt** [comment]
Hi Sonichandni, yes l have changed the database but the error still persist.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by developers-desk** [comment]
Can you send me the screenshot, because it working fine in my system.

**Comment by lampatt** [comment]
Thank you Sonichandni, please find attached screen shots of the errors am encountering.

Thank you
________________________________

**Comment by developers-desk** [comment]
Hey,
I could not able to find the screenshot.

**Comment by lampatt** [comment]
Hi SoniChandni,

Please find attached the screen shot am sending again.

Thanks
________________________________

**Comment by developers-desk** [comment]
Hi Patrick,

Sorry but again I can not able see any screen shot here.
just have a look at this screen shot what I am getting is just a message.
[click here to see the screen shot](https://prnt.sc/nn3u57)

Thank you

**Comment by lampatt** [comment]
Thanks Sonichandni for your mail. Its rather unfortunate not been able to see the screen shot again, but l have attached it again in a zip file called Error.zip.

Hope it gets delivered this time or if you can suggest any other better way to send them to you.

Anyway hope you see it this time

Thanks very much for you support, really appreciate

Patrick
________________________________

**Comment by developers-desk** [comment]
Hi,

There is a problem with gmail, because of security reasons it will not accept the zip file. It assumes that there is a malware so it will not pass it.

you can use **Lightshot (screenshot tool)** it is a chrome/Firefox extension for taking screen shots of the screen and convert it into shareable link.

Thanks,
Chandni

**Comment by lampatt** [comment]
Thank Sonichandni

please find below the screen shots l capture using the lightshot tool you directed me.

https://prnt.sc/nro7a1

https://prnt.sc/nro958

https://prnt.sc/nrojmk

https://prnt.sc/nroqxy


l also had the following error message when importing the database:

SQL query:


--
-- Constraints for dumped tables
--
--
-- Constraints for table `attendance_mba_sem1`
--
ALTER TABLE `attendance_mba_sem1`
  ADD CONSTRAINT `attendance_mba_sem1_ibfk_1` FOREIGN KEY (`date`) REFERENCES `days` (`date`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `attendance_mba_sem1_ibfk_2` FOREIGN KEY (`s_enrl`) REFERENCES `student` (`s_enrl`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `attendance_mba_sem1_ibfk_3` FOREIGN KEY (`usub_id`) REFERENCES `subject` (`usub_id`) ON DELETE CASCADE ON UPDATE CASCADE
MySQL said: Documentation

#1452 - Cannot add or update a child row: a foreign key constraint fails (`sams`.`#sql-1070_46`, CONSTRAINT `attendance_mba_sem1_ibfk_2` FOREIGN KEY (`s_enrl`) REFERENCES `student` (`s_enrl`) ON DELETE CASCADE ON UPDATE CASCADE)

thanks
________________________________

**Comment by lampatt** [comment]
________________________________

**Comment by lampatt** [comment]
Thank Sonichandni

please find below the screen shots l capture using the lightshot tool you directed me.

https://prnt.sc/nro7a1

https://prnt.sc/nro958

https://prnt.sc/nrojmk

https://prnt.sc/nroqxy


l also had the following error message when importing the database:

SQL query:


--
-- Constraints for dumped tables
--
--
-- Constraints for table `attendance_mba_sem1`
--
ALTER TABLE `attendance_mba_sem1`
  ADD CONSTRAINT `attendance_mba_sem1_ibfk_1` FOREIGN KEY (`date`) REFERENCES `days` (`date`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `attendance_mba_sem1_ibfk_2` FOREIGN KEY (`s_enrl`) REFERENCES `student` (`s_enrl`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `attendance_mba_sem1_ibfk_3` FOREIGN KEY (`usub_id`) REFERENCES `subject` (`usub_id`) ON DELETE CASCADE ON UPDATE CASCADE
MySQL said: Documentation

#1452 - Cannot add or update a child row: a foreign key constraint fails (`sams`.`#sql-1070_46`, CONSTRAINT `attendance_mba_sem1_ibfk_2` FOREIGN KEY (`s_enrl`) REFERENCES `student` (`s_enrl`) ON DELETE CASCADE ON UPDATE CASCADE)

thanks

________________________________

**Comment by lampatt** [comment]
Greetings my friend. Hope you good. Wanted to know if you did received my mail with the screenshots links l sent you and if there is anything l need to do to rectify the errors.

Thank you so much

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by developers-desk** [comment]
Hey Patrick,

Sorry for the delay. I was busy these days. I got  your all screenshots. and I have gone through it. I will look into it and update you.

Thank you

**Comment by lampatt** [comment]
Thank you very Sonichandni for your time out of your busy schedule. I appreciate. I will wait for your update.

Thanks, God bless you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by divyansh0203** [comment]
Facing same error.. in foreach() .plz help
